### PR TITLE
upgrade redis dependency

### PR DESCRIPTION
**Pull request by angusluk**
redis 4.0 was released since 2017 July.
We will need to upgrade redis version

https://redislabs.com/blog/redis-4-0-0-released/

### CODE REVIEW

**Comment by AndyObtiva** [comment]
This is an open-source project. Get off your ass and fork/change yourself! Once done, submit a pull request, and I'll merge in if all is good once I'm free.

**Comment by angusluk** [comment]
want to know, if you consider merge the redis dependency branch to your master branch?
already submit a pull request.
thanks

**Comment by angusluk** [comment]
spec reports already sent to https://codeclimate.com
screenshot 2019-01-22 at 1 05 13 pm

**Comment by AndyObtiva** [comment]
I'm sorry I don't feel comfortable accepting anything from you.

**Pull request closed without merging**
